USE [master]
GO

/****** Object:  Database [vizsga]    Script Date: 2024. 04. 19. 15:34:31 ******/
CREATE DATABASE [vizsga]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'vizsga', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\vizsga.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'vizsga_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\vizsga_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vizsga].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vizsga] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vizsga] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vizsga] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vizsga] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vizsga] SET ARITHABORT OFF 
GO

ALTER DATABASE [vizsga] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [vizsga] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vizsga] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vizsga] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vizsga] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vizsga] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vizsga] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vizsga] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vizsga] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vizsga] SET  ENABLE_BROKER 
GO

ALTER DATABASE [vizsga] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vizsga] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vizsga] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vizsga] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vizsga] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vizsga] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [vizsga] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vizsga] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [vizsga] SET  MULTI_USER 
GO

ALTER DATABASE [vizsga] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vizsga] SET DB_CHAINING OFF 
GO

ALTER DATABASE [vizsga] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [vizsga] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [vizsga] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [vizsga] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [vizsga] SET QUERY_STORE = OFF
GO

ALTER DATABASE [vizsga] SET  READ_WRITE 
GO

