// <auto-generated />
using Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240419114433_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KategoriaNev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriak");
                });

            modelBuilder.Entity("Backend.Models.Teszt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Helyes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("V1");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Kerdes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("V4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.ToTable("Tesztek");
                });

            modelBuilder.Entity("Backend.Models.Teszt", b =>
                {
                    b.HasOne("Backend.Models.Kategoria", "_Kategoria")
                        .WithMany("_Tesztek")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("_Kategoria");
                });

            modelBuilder.Entity("Backend.Models.Kategoria", b =>
                {
                    b.Navigation("_Tesztek");
                });
#pragma warning restore 612, 618
        }
    }
}
